---
- name: Installer les paquets requis (RedHat/CentOS)
  ansible.builtin.dnf:
    state: present
    disable_gpg_check: yes
    name:
      - openldap
      - openldap-servers
      - openldap-clients
      - python3-ldap
